wikimedia/restbase-mod-table-cassandra

- lib/db.js
- lib/dbutils.js
- lib/secondaryIndexes.js
- test/index.js
Until now, values were only sporadically converted between rb-cassandra and Cassandra types. This PR resolves this, and systematically converts values from JS to Cassandra when issuing queries, and back to JS after fetching the result rows. It also introduces conversion schemes for set values whose underlying types need conversion (such as set<varint>, set<josn>, etc.).
This PR aims at resolving [T84900](https://phabricator.wikimedia.org/T84900)
> Proper conversion to/from JS when issuing queries to Cassandra

- index.js
Remove the inline spec, and export operations only. This is intended to be
used with
https://github.com/gwicke/restbase/commit/fce27d997d4cfc46843b0b321dd2916bc8c0625b.
TODO: 
- Figure out a way to run the tests with spec & module
- Distribute the spec & tests separately as `restbase-spec-sys-table`?
- Actually change the npm package name to `restbase-mod-table-cassandra`
> WIP: Convert restbase-cassandra into a new-style module

- index.js
Patch the export object of restbase-mod-table-cassandra to export the module_info property as well (albeit not containing any useful info for now).
> Export the module_info property

- table.yaml
- test/index.js
- test/test_router.js
RB-Cassandra hasn't lost any of its functionalities, but due to the change in module exports, the tests were not passing. This PR makes the tests conform to the new scheme. It translates the new module export object to *routeswitch* handler format, checking for exported `operationId`s in the process.
> Make tests pass

- package.json
Also switch to cassandra-driver release 1.0.3, which has our keepalive fixes.
> Release restbase-mod-table-cassandra v0.3.0

- lib/db.js
- lib/dbutils.js
- test/index.js
Build up & pass along type hints, so that batch queries with ambiguous numeric
types work despite the cassandra driver's lack of prepare support in batches.
In practice, this means that tables containing ints or floats now work even if
they have secondary indexes defined.
There is still a warning emitted from the cassandra driver for some reason,
but the actual requests go through as verified by the following read tests.
Bug: https://phabricator.wikimedia.org/T88690
> Supply type hints to cassandra driver batch queries

- lib/dbutils.js
- package.json
- Apply type conversions for all non-null values, not just to truthy values
- Replace identityConversion with null, saves one function call for buffers
(common)
- Simplify convertRow: use Object.keys.forEach() instead of for (var i in
obj), remove unnecessary arg checks
> Small performance & correctness tweaks

- lib/dbutils.js
- test/index.js
When inserting into a table, we should use INSERT instead of an UPDATE
whenever all of the non-PK attributes are null, or are thought of as
being null by Cassandra, such as empty arrays and objects. This commit
fixes this issue and correctly determines which one to use.
> Fix: Cover edge case of all provided attributes being null

- lib/db.js
- lib/index.js
- Important for multi-DC operation, so that localQuorum etc knows what is
actually local
- Create tables in localDc by default. In the longer term, this should
probably load the cluster state from system.local & system.peers instead.
> Support for specifying the localDc parameter

- index.js
- lib/db.js
- lib/dbutils.js
- lib/secondaryIndexes.js
- test/index.js
This patch prefixes a private `_domain` key element to each hash key, which in
turn lets us share a single CF for several domains. With this patch, all but
two listing tests (for titles and revisions) in restbase are passing. This is
the expected consequence of our strategy of using compound primary keys. The
ability to list hash keys can be restored later using secondary indexes.
Also:
- Introduced an `InternalRequest` class and a `_makeInternalRequest` method to
set up and systematically handle request-related state. This cuts down the
number of positional parameters drastically and replaces common boilerplate
in `get()`, `put()`.
- Removed the now-dead `getSchema` and `_getSchema` methods. This
functionality is now provided by `_makeInternalRequest`.
- Prepared for a removal of the …
> Add ability to share column families between domains

- lib/dbutils.js
This is a very hot function as it's applied to all result rows. Also removed
the per-row convertRow method, as it's not actually needed.
Notes:
- using `delete` to remove private attributes is slower than reconstructing
the entire row
- pre-allocating the Array & then iterating over it is faster than `map`
- there is some potential to be even faster with in-place updates by setting
private attributes to `undefined`, but that's somewhat ugly as it doesn't
actually remove those keys from `Object.keys()`.
> Performance: Optimize convertRows

- .jshintignore
- lib/db.js
- lib/dbutils.js
Meta tables track the table schema and potentially other table metadata, which
can't differ between domains. Thus, don't multiplex on domain for meta tables.
This avoids per-domain table creation & schema update attempts.
> Don't multiplex meta tables across domains

- .jshintignore
- .jshintrc
- .travis.yml
- index.js
- lib/db.js
- lib/dbutils.js
- lib/index.js
- lib/secondaryIndexes.js
- package.json
- test/index.js
- test/test_router.conf.yaml
- test/test_router.js
The new version of [the datastax cassandra driver](https://github.com/datastax/nodejs-driver) brings several improvements:
- Built-in encoding & decoding of non-native types (previously handled by our own cassandra-codec package). This is done without binary modules, which now makes the cassandra backend pure JS only.
- App-level hartbeats and better error handling. This should hopefully fix the occasional hangs we saw when nodes went down.
Since this is a major upgrade we should test it thoroughly before deploying it in production. With the combined test coverage of this module & restbase I am fairly confident though that it is doing the right thing™.
> Cassandra driver v2 integration

- lib/index.js
- Our previous policies were actually not used at all. They are supposed to be
set in a 'policies' object rather than directly on the client options. This
explains why reconnections were still so slow.
- Call connect() on the client before building the DB object. This provides an
early failure detection.
> Clean up the cassandra driver configuration

- maintenance/thin_out_key_rev_value_data.js
- Don't use the native driver's stream / forEach capability. They lack
back-pressure and have less than perfect error handling, even with the
custom RetryPolicy added here. For example, when encountering tombstone
overwhelm we need to slow down to paging one item at a time in order to have
a chance of making any progress at all.
- Print the pageState on error & support resuming by passing it in
- Drop delays.
> Update with changes from production

- lib/db.js
- package.json
A bug in Cassandra 2.1 causes inserts in tables with native secondary indexes
on _domain to fail if the size of any column value exceeds a fairly low
threshold (16k IIRC). This is a problem especially on tables backing content
tables like those behind key_rev_value storage.
This patch stops creating those secondary indexes by default. This will break
the hacky revision and title listings in RESTBase, which we should disable or
replace with API requests.
Next steps in the backend:
- Automatically drop existing secondary indexes on `_domain`. Naming scheme is
`<table_name>_<column_name>_idx_<counter>`, with the main difficulty being
the counter value.
> Stop creating native Cassandra indexes on _domain

- .gitignore
- lib/db.js
- lib/dbutils.js
- lib/revisionPolicy.js
- lib/secondaryIndexes.js
- test/index.js
- test/revision_policies.js
This branch:
* implements a test case for a policy of `latest`
* adds support for CQL generation of `USING TTL` queries
* adds an async-safe utility method for performing arbitrarily large Cassandra queries, and paging through the results
* adds `RevisionPolicyManager` (currently supports policy types of `all`, and `latest`), and wires it into a refactored `DB#_rebuildIndexes` (renamed `DB#_backgroundUpdates`).
See: https://phabricator.wikimedia.org/T94524
> implement revision retention policy

- lib/db.js
- lib/dbutils.js
- package.json
- test/revision_policies.js
Instead, add the default in makeSchemaInfo. This makes new schemas compatible
with existing schemas, and thus avoids breakage or the need for schema
migration.
> Don't set the default retention policy in the schema itself

- index.js
- lib/db.js
- lib/dbutils.js
- lib/schemaMigration.js
- package.json
- table.yaml
- test/dbutils.js
- test/schema_migrations.js
This makes it possible to migrate from one revision retention policy to another (or from none / the default).  More generally, it provides the framework by which additional schema migration can be implemented as well.
Note: In the absence of an explicitly defined schema version, the new default becomes 0.  This means that existing RESTBase installations will need to have their schema versions explicity set to 1, (that will be handled in a separate pull request against wikimedia/restbase).
See: https://phabricator.wikimedia.org/T96612
> revision retention policy schema migration

- lib/db.js
- lib/schemaMigration.js
- package.json
- test/schema_migrations.js
- test/test_router.js
Adds an implementation of schemaMigration.Attributes (which previously
inherited Unsupported).  Iteratatively adds and/or removes the delta
attributes of two schemas.
Bug: T97073
> schema attribute addition/removal

- lib/schemaMigration.js
Don't fail if columns to add already exist, or columns to remove don't exist
any more. This make sure that racing workers eventually make progress with
schema updates.
> Be robust against schema update races

- maintenance/thin_out_key_rev_value_data.js
- Clean up row state
- Add a method / example for re-rendering HTML within a time range (used to
clean up recent Parsoid corruption event)
> Update thin-out script from production

- test/dbutils.js
- test/revision_policies.js
While being related to revision retention policy, the affected tests
test validation of the schema, and are thus better treated as unit
tests in `test/dbutils.js`.
This is also necessary to break the tests dependency on dbutils,
(relevant to T103406).
Bug: T103406
> move schema validation tests to dbutils

- lib/db.js
- lib/dbutils.js
- lib/revisionPolicy.js
- lib/secondaryIndexes.js
- package.json
- test/index.js
When a record is added/updated, the asynchronous updates kick in to update the secondary indices and enforce the declared retention policy. However, the original request's attributes are JS types, while all of the retrieved DB rows for which these actions are applied are in native, Cassandra representation, while the code supposed both were JS.
This PR fixes this issue by adding an additional parameter to `buildPutQuery()` and `buildCondition()` allowing users to supply their own conversion function which is applied to a request's query's attributes. This feature is used by the revision policy and the secondary index rebuilder, which supply `dbu.noConvert()`, a dummy conversion function simply returning the value passed in. If this extra parameter is not passed to `buildPutQuery()`, the …
> Normalise asynchronous updates and release v0.7.0

- .gitignore
- lib/dbutils.js
- package.json
- test/functional/invalid_requests.js
- test/functional/multi_ranged.js
- test/functional/revision_policies.js
- test/functional/schema_migrations.js
- test/functional/secondaryIndexes.js
- test/functional/simple.js
- test/functional/varint.js
- test/unit/delete.js
- test/utils/test_router.js
- test/utils/test_utils.js
More refactoring is needed on tests to allow moving them to a separate module.
- Replaced cassandra driver's uuid with our cassandra-uuid lib. As constructor is checked by driver, replaced TimeUuid objects with strings everywhere as strings should be correctly handled by both implementations. 
- Removed dependency from functional tests to dbutils: moved testTidFromDate to test_utils as it's used only by tests. Also removed the use of hash function and started to compare plain schema objects which should be fine bc 'hash match' === 'objects match'
- 2 tests were failing - they received unexpected `revisionRetentionPolicy = [ undefined ]`, so I set this schema property only when it's non-empty.
- Fixed one before which didn't return the promise and so could swallow an error.
- Refactored …
> More tests refactoring in preparation to move to a separate module

- lib/db.js
- lib/dbutils.js
- package.json
Bug: [T104581](https://phabricator.wikimedia.org/T104581)
> Make exception handling more robust for background updates and release v0.7.3

- lib/db.js
The missing limit functionality here is causing rewrite bursts with on the
order of hundreds of queries per second, which causes OOM and compaction to
lag behind.
This is a hotfix, intended to stop the bleeding until we can clean this up
more thoroughly.
Bug: https://phabricator.wikimedia.org/T105509
> Hotfix: Force limit to actually work on secondary index updates

- lib/db.js
- lib/dbutils.js
- lib/revisionPolicy.js
- test/unit/dbutils.js
Refactored dbu#buildGetQuery to treat the default projection (*), as an
explicit set of attributes.  This avoids the special-casing for 2.0.x versions,
and makes appending TTL attributes more straightforward.
Introduced a boolean parameter to db#_getRaw and dbu#buildGetQuery to specify
results that include a TTL attribute for all candidates (candidates being any
non-index, non-collection attribute).
Added TTL results to the queries performed in db#_backgroundUpdates, and
utilized them to avoid rewriting rows that have already had a TTL set.
Bug: T105509
> avoid unnecessary TTL rewrites

- maintenance/thin_out_key_rev_value_data.js
When thinning both html and data-parsoid it's easier to maintain a clean
cut-off when comparing with a fixed date.
> Compare with a fixed date

- package.json
- https://github.com/datastax/nodejs-driver/releases/tag/v2.1.0
- https://github.com/datastax/nodejs-driver/releases/tag/v2.1.1
- https://github.com/datastax/nodejs-driver/releases/tag/v2.1.2
> Update cassandra-driver to 2.1.2

- lib/db.js
With idempotent updates it is better to retry the put at a higher level if
necessary. Consumers can still choose to ignore failures, but now have a
chance to repeat requests in case any part of the request processing fails.
This change should provide better back-pressure in write overload situations
by slowing those requests down until the request is fully processed. As a
consequence, it should reduce the memory build-up in restbase when writes are
slow.
As a 'small' bug fix, this patch also makes sure that background updates are run
whenever a retention policy other than 'all' is specified, even if no
secondary indexes are defined on the table.
> Make background updates synchronous

- lib/db.js
- lib/dbutils.js
- package.json
- test/functional/backend_migrations.js
- test/unit/dbutils.js
Given the case where *both* a backend version migration, and a table
storage schema migration are needed, it stands to reason that the latter
might depend on the former.  Because of this, the two cases need to be
treated separately, and table schema migration must occur after any backend
migration has completed.
This changeset introduces a `_backend_version` attribute to the schema blob
but does not consider it when generating the hash.  DB#_createTable
first evaluates `_backend_version`, performs a back-end migration if
necessary, then compares hashes and performs a table schema migration if
necessary.  Finally, if any changes were made, the persisted schema blob
is updated.
Bug: T97845
> back-end versioning

- lib/revisionPolicy.js
- package.json
The PR implements an interval option for revision retention policy for Cassandra backend using and algorithm, described in a ticket.
Note: this PR depends on spec one: wikimedia/restbase-mod-table-spec#12
Bug: https://phabricator.wikimedia.org/T94524
> Implemented 'interval' policy support

- lib/schemaMigration.js
For page-related information we would need to be able to add static columns to the schema. This PR adds this capability to Cassandra and SQLite.
This PR depends on tests in https://github.com/wikimedia/restbase-mod-table-spec/pull/14
> Added support for static column additions

- .travis.yml
Travis now supports starting up services with the 'services' stanza. This lets
us avoid using sudo & thus use the container infrastructure. As a result, our
tests should run faster. It also simplifies our .travis.yml slightly.
> Use Travis' new services stanza

- lib/db.js
In 7fd61430a8cf50 the restbase-mod-table-spec module gained the ability to
sort index keys logically. When applied to new schemas only, this caused a
hash mis-match and thus an apparent schema change, which in turn caused
RESTBase to fail to start. Because of another issue in the service runner
logging code the reason for the start-up failure wasn't immediately clear (see
https://github.com/wikimedia/service-runner/pull/46). With that patch applied,
the failure revealed itself as
https://gist.github.com/gwicke/0a4bd4a1e8635df2aa28.
This patch applies the schema normalization to both stored and new schemas,
which eliminates the cause of the hash mis-match. With this applied, RESTBase
starts up successfully in staging. A similar patch needs to be applied in the
sqlite backend.
> Normalize stored schemas before hashing

- lib/db.js
- lib/dbutils.js
- lib/schemaMigration.js
- package.json
There was an idea to drop a by_ns secondary index, this adds a test for this feature in backends.
I'm wondering, if we should actually drop the table, or just store an updated schema? I'd better alter this PR and do the latter, to have 100% protection agains data corruption. And the tables could then be deleted manually. What do you think?
Bug: https://phabricator.wikimedia.org/T111959
> Added support for secondary index removal

- lib/db.js
- lib/index.js
- package.json
- test/functional/replication.js
- test/utils/test_client.conf.yaml
In `DB#createTable`, validate that current keyspace replication meets requirements (based on the list of datacenters from module configuration, and any durability options in the request), and adjust if necessary.
Bug: https://phabricator.wikimedia.org/T108613
> multi-datacenter replication

- lib/db.js
- lib/secondaryIndexes.js
In the brave new world of multiple datacenters, when we say `one`, we
really mean `localOne`.
Bug: https://phabricator.wikimedia.org/T108613
> Use `localOne` as default

- lib/schemaMigration.js
- package.json
We cannot actually drop a secondary index tables during the deploy, as other nodes would fail to update the secondary index. So, just update the metadata for now.
> Removed actual deleting of secondary index tables

- lib/db.js
- test/mocha.opts
Only update replication factor checks / updates once per keyspace. Without
this caching and given a long list of domains, startup takes on the order of
minutes *per worker*.
> Cache replication factor updates

- lib/db.js
- lib/dbutils.js
- lib/schemaMigration.js
- package.json
- Remove the keyspaceSchemaCache, and make the schemaCache purely
keyspace-based. Document caches better.
- Encapsulate the keyspaceSchemaCache handling in _keyspaceName().
- Don't wipe all caches when creating a new table, or migrating a schema.
- Retry transient errors in schema retrieval when a second request indicates
that the keyspace and table now exists.
- Improve logging in schema migrations.
- Avoid allocations and delete in schema hashing code.
> DB schema caching & migration cleanup

- lib/db.js
- lib/dbutils.js
- package.json
When we try to insert a field that's not in the schema, cassandra silently ignores that and SQLite is throwing a non-descriptive error. However, extra fields clearly indicate a bug in the client - either on table schema, or on a query, so we need to fail-fast and throw an error.
> Added a check for non-existing columns on insert

- lib/db.js
- lib/dbutils.js
- lib/revisionPolicy.js
- package.json
In cassandra we start looking at a `revisionRetentionPolicy` starting from a row just after the row we've just inserted. This needs to be updated to support policy with `count === 0`, that just set a graceTTL.
Also, there's been a bug in buldGetQuery - when `withTTLs` option was provided it failed with a 500 error.
SQLite module doesn't need updates, spec module is updated with a test.
> Implemented support for a revisionRetentionPolicy with 0 count

- lib/dbutils.js
- package.json
This PR adds mapping of `long` schema type to `bigint` cassandra type.
Clients supply longs as strings due to Javascript Number precision limitations.
> Support long type mapped to bigint

- lib/db.js
- lib/dbutils.js
- lib/schemaMigration.js
- Generalize option CQL generation in dbutils.
- Support hinting for the expected update pattern:
```
updates: {
pattern: 'random-update', // or 'write-once', 'timeseries'
}
```
This hint is then used to optimize storage parameters. In Cassandra, this
influences the compaction strategy selection. In SQLite, this option is
currently ignored.
- Add option migration support.
> Support update pattern hinting and option migrations

- lib/db.js
- package.json
Setting `_ttl` was already supported in cassandra, just need to look if it was provided by an external request.
> Support custom _ttl attributes for individual rows

- lib/db.js
- lib/dbutils.js
- lib/schemaMigration.js
- package.json
Travis has cassandra 2.0.9, which doesn't support DTCS, so before applying a `timeseries` update hint we need to check that cassandra supports it. Support was added in 2.0.11 and 2.1.1.
> Hints: Check cassandra version before applying DTCS hint

- .jscs.json
Latest jscs seems to have started to disallow constructs of this form by
default:
if (something) {
return a;
} else {
return b;
}
I personally think this form is fine, especially if the branches are short.
The existing code also uses this quite often.
> Don't require early returns

- lib/db.js
- package.json
There's a whole bunch of bugs being fixed here:
- The TTL policy didn't work on cassandra, but that was unnoticed because of a bug in the test. The problem is that TTL is column-based in cassandra, so to actually set a TTL when writing a row, we need to have at least one non-null non-primary-key value in the row. But in revPolicy update code, we were fetching only key columns and those needed for secondary indexes, so for tables with no sec indexes TTL was not set up. Easy to fix by dropping the custom proj and fetching everything. We don't loose to much on the speed here, because it affects only a single row.
- After that being fixed, I've run into a bug in cassandra, that affects our tests. The bug is present in 2.1.* but fixed in 2.2.*. The problem was, that when you add a static …
> Fixed TTL revPolicy and removed support for individual rows ttl

- .travis.yml
Tests the module against the same cassandra version we use in production. 
> Travis: Install custom cassandra version to match production

- lib/db.js
- lib/revisionPolicy.js
- package.json
In our system every db entry has a tid, which for us works as internal cassandra timestamp. We've used to assign the write timestamp the same as tid, so when we wanted to overwrite the value, there was a conflict and a new value was chosen by cassandra in unpredictable manner. 
Also, some miner improvements to revision policies are made: as we don't mess with timestamps any more, we rely on tid in the retention policy, which is actually way more correct.
Test here: https://github.com/wikimedia/restbase-mod-table-spec/pull/35
> Don't mess with write timestamps and allow overwriting rows

- lib/index.js
- package.json
Fixes the last commit that typo'd maxVersion as maxProtocolVersion
Bug: https://phabricator.wikimedia.org/T126629
> Set maxVersion 3 for the duration of the Cassandra upgrade

- maintenance/thin_out_key_rev_value_data.js
This should delete everything older than midnight 2015-12-31.  I have tested it with the query commented out, and the output looks right.
Bug: https://phabricator.wikimedia.org/T140008
> Hack thin-out script to remove everything older than Dec 2015

- package.json
Some time ago we've switched to driver to our own fork that replaced `async` lib with `neo-async` to get some boots in performance and memory consumption. However, during that time a lot of work has been done on the upstream driver. For instance, `async` dependency was removed completely.
Current `neo-async` branch is equal to driver's `3.0.1` version.
I've done some basic testing of the new driver and it seems to work correctly. Performance is ~15% better then with our current version and memory consumption decreases from 220 Mb to 160 Mb per worker under load.
Testing in staging is required for this change, so bumping the version to `0.10`.
> Update driver to v3.1.1

- maintenance/lib/index.js
- maintenance/lib/iterateTable.js
- maintenance/thin_out_key_rev_value_data.js
- maintenance/thin_out_parsoid.js
Moves title iteration out to its own module, and re-uses it to create a Parsoid-specific thinning script.  This new script performs corresponding deletes to data-parsoid as part of a batch operation.  Since both entries share the same partition key, this is atomic, isolated, and performant.
This is still quite rough, but I wanted to get it put up, and more eyes on it, before taking it much further.
Comments appreciated.
> key_rev_value-based revision culling

- index.js
- package.json
Reduce the verbosity of storage backend errors by not including full request
bodies in the error object. Instead, the body is serialized to a JSON string,
and only the first 200 bytes of this string are returned.
Task: https://phabricator.wikimedia.org/T141384
> Do not include the full request body in errors

- lib/db.js
- lib/dbutils.js
- lib/revisionPolicy.js
- package.json
For the TTL policy we can avoid doing 'write -> read -> update' pattern because we always know that the TTL will be set, so we can skip the normal revision policy update and write with TTL right away.
Bug: https://phabricator.wikimedia.org/T150703
> Optimise the TTL revision retention policy

- lib/db.js
- lib/dbutils.js
- lib/index.js
- lib/revisionPolicy.js
- lib/schemaMigration.js
- lib/secondaryIndexes.js
- maintenance/lib/index.js
- maintenance/thin_out_key_rev_value_data.js
- maintenance/thin_out_parsoid.js
- package.json
The new driver version is released and it has built-in promise support - let's use it!
I've measured the performance locally a bit, but no significant difference was found, need to run a dump in staging to get more data.
Bug: https://phabricator.wikimedia.org/T156441
> Update to a newer cassandra driver and use built-in promise support

- lib/db.js
- package.json
Schema migrations are significant events and can take a long time, so
should be brought to operators' attention by logging them at the "warn"
level.
> Log schema hash mis-matches / migrations at "warn" level; v0.11.1

- lib/db.js
The `system.schema_columnfamilies` table doesn't exist any more, see https://issues.apache.org/jira/browse/CASSANDRA-10996
> Switch to system_schema.* keyspace for checking if the meta table exist

- index.js
- lib/db.js
- lib/dbutils.js
This one is not quite ready, because we need to adapt the tests and we need to check that RESTBase will not be broken by this, so created a PR to engage the discussion early on. 
Currently we're adding the implicit `tid`(or `_tid`) to all the tables, so we never overwrite the values, we're writing the new value with a new TID and then apply some retention policy. However, since we've got rid of the revision policies, we don't really need to have TID in every schema - it's a too magical and not manageable without retention policies. 
With this change we will be able to convert the `key_value` bucket to use overwriting instead of a rev policy, also we'd be able to create the `timeline` indexes.
Thoughts?
Bug: https://phabricator.wikimedia.org/T170902
> Remove implicit _TID adding

- lib/dbutils.js
- package.json
As we're removing the `revisionRetentionPolicy` from the storage module, we need another way to specify table-level TTLs. So expose the `default_time_to_live` configuration property.
This will also need some changes to the restbase key_rev_value.
Bug: https://phabricator.wikimedia.org/T170901
> Expose default_time_to_live

- lib/db.js
- lib/schemaMigration.js
- package.json
This will dry-dun the actual Cassandra schema alternation.
> Support dry-run for schema migrations

- lib/db.js
- lib/dbutils.js
- lib/schemaMigration.js
- package.json
Tested locally that this indeed clears up meta tables from compression/compaction settings without issuing any table alternations. Would be good to deploy this together with a RESTBase PR that would clear up update patterns from the schemas.
> Remove automagic compression/compaction settings and migrations.

- lib/dbutils.js
- lib/schemaMigration.js
- package.json
fast-json-stable-stringify is being used because it does not have any dependencies and has been shown to be faster than json-stable-stringify
Bug: [T210426](https://phabricator.wikimedia.org/T210426)
> Replace `json-stable-stringify` with `fast-json-stable-stringify`

- lib/dbutils.js
- package.json
For RESTBase split some of the legacy tables that we want to reuse were created with string value type. For unusual content-types, like mml or svg we need to stringify the buffer that the backend is receiving.
> Stringify a Buffer if we want to write it into string type.

- .eslintrc.yml
- lib/db.js
- lib/schemaMigration.js
- package.json
- test/functional/replication.js
Now in case the request to create bucket came with a `*` domain, it will create the bucket for all the defined storage groups.
> Create keyspaces for all storage groups if * domain is provided
