wikimedia/restbase-mod-table-cassandra

index.js
lib/db.js
test/index.js
test/test_router.js

This is still work in progress.
https://phabricator.wikimedia.org/T85640
Task list -
[ X ] convert  the byte array to token and append that to next url 
[ X ] think on what happens if malicious users pass in random (or not so random) tokens.

Add paging support (T85640)

---

lib/db.js
test/index.js

This fixes https://phabricator.wikimedia.org/T75815

enable float type

---

lib/db.js

And link to the phabricator task.

Add a comment about index processing

---

lib/db.js
lib/dbutils.js
package.json
test/index.js

Bug: https://phabricator.wikimedia.org/T90027

Add support for compression hints in schema options

---

lib/db.js
package.json

Also clean up the dependencies slightly.

Hotfix: Don't crash in the page path

---

Readme.md
index.js
lib/db.js
lib/dbutils.js
lib/index.js
package.json
test/index.js

Rebased and fixed up hardik's https://github.com/wikimedia/restbase-mod-table-cassandra/pull/47. Also added a fast path for the typical start-up case where the table existst, the schema checks out and nothing is to be done.

Schema checks

---

lib/db.js
lib/dbutils.js
test/test_router.js

Use storage groups to determine domain to keyspace mappings.
Bug: [T91188](https://phabricator.wikimedia.org/T91188)

Storage groups

---

lib/db.js
package.json

Create Cassandra-native secondary indexes on the `_domain` attribute.

also index _domain attribute of new columnfamilies

---

maintenance/thin_out_key_rev_value_data.js

Bug: https://phabricator.wikimedia.org/T94196

Add maintenance script to thin out renders in a key_rev_value table

---

lib/index.js

Task: https://phabricator.wikimedia.org/T98934

Increase the max schema agreement wait time

---

lib/dbutils.js
test/index.js

This pull request fix and add tests for the following cases
1. Fix and add a test cases for static columns
2. Fix cases where proj = "*" in req
3. Add a test case for 'order by' in Get

Add missing test cases and fix static columns

---

package.json

Release v0.6.6

---

package.json

This matches the version of bluebird we are using in restbase.

Upgrade bluebird to 2.8.2 and release v0.6.7

---

lib/db.js
lib/dbutils.js

- Set a small fetch size of 5 rows at a time
- Break up the promise chain at each page boundary

Bound memory used by background updates

---

package.json

Bug: https://phabricator.wikimedia.org/T104284

Bump version after re-upload to fix sha1sum

---

lib/db.js
lib/dbutils.js
lib/revisionPolicy.js

A follow-up nit from https://github.com/wikimedia/restbase-mod-table-cassandra/pull/122
Bug: T105509

rename _maxTTL to _ttl

---

maintenance/thin_out_key_rev_value_data.js

- add exponential back-off, so that temporary issues are more likely to
resolve themselves
- match >= on tokens and domain/key matches for more effective retry on an
existing key after a failure

Implement exponential retry back-off

---

maintenance/thin_out_key_rev_value_data.js

- Print token on each deletion
- Print progress every 500k entries
- Minor formatting cleanup

Misc cleanup

---

maintenance/thin_out_key_rev_value_data.js
package.json

- automatically step over problematic token ranges
- consistently report the current token range

Improve the thin-out script

---

lib/db.js
lib/dbutils.js
package.json
test/unit/dbutils.js

Use a common validator for schema validation. Also, adds support for where conditions like in [docs](https://github.com/wikimedia/restbase/blob/master/doc/TableStorageAPI.md)
```
{
table: 'example',
attributes: {
name: 'Tom',
property: {
gt: 'a',
le: 'c'
}
},
// Only select the 'value' column
proj: ['value']
limit: 50
}
```
(note two conditions in `property`) 
This PR depends on a spec PR, so travis is expected to fail.

Use common validator

---

Readme.md
doc/SecondaryIndexes.md

- Update the README to be less blatantly out of date.
- Add SLIK paper reference in SecondaryIndexes doc.

Some doc updates

---

Readme.md
lib/index.js

https://phabricator.wikimedia.org/T111113

make TLS connections to Cassandra configurable

---

lib/db.js
package.json

Also:
- DB#_getReplication() uses metadata already loaded in the driver
- extracted module field from internal method

Upgrade Cassandra driver to 2.2.1

---

lib/db.js
lib/dbutils.js
lib/schemaMigration.js
package.json

Version check

---

.jscs.json
index.js
lib/db.js
lib/dbutils.js
lib/index.js
lib/revisionPolicy.js
lib/schemaMigration.js
lib/secondaryIndexes.js
package.json
test/index.js

- Updated dependencies
- Integrated jscs
- Fixed styling errors

Update dependencies and integrate jscs

---

lib/db.js
lib/schemaMigration.js
package.json

- Updated bluebird version
- Updated dependencies
- Updated code to use new fancy features of bluebird
Depends on https://github.com/wikimedia/restbase-mod-table-spec/pull/31 being merged and released.

Updated to bluebird 3

---

lib/db.js
lib/dbutils.js
package.json
test/unit/dbutils.js

See https://github.com/wikimedia/restbase-mod-table-spec/pull/34

TTLs: added support to get and set TTLs for individual rows

---

lib/db.js
lib/dbutils.js
lib/revisionPolicy.js
package.json

See https://github.com/wikimedia/restbase-mod-table-spec/pull/36

Rev Policy: Implemented latest_hash policy

---

package.json

Driver upgrade

---

lib/index.js
package.json

Bug: https://phabricator.wikimedia.org/T126629

Set maxProtocolVersion 3 for the duration of the Cassandra upgrade

---

lib/db.js
maintenance/keyspace_name.js
maintenance/lib/index.js
maintenance/thin_out_parsoid.js

Simple script to fetch the calculated Cassandra keyspace name for a given RESTBase config.

Keyspace name script

---

.eslintrc.yml
.travis.yml
index.js
lib/db.js
lib/dbutils.js
lib/index.js
lib/revisionPolicy.js
lib/schemaMigration.js
lib/secondaryIndexes.js
package.json
test/index.js

Continue the journey for updating our stuff to ES6

Update dependencies, update to ES6, use eslint

---

.travis.yml

Switch travis to cassadnra 3

---

index.js
lib/dbutils.js
package.json
test/index.js

Bug: https://phabricator.wikimedia.org/T184199

Rename to remove -ng suffix; Bump version to 0.12.2

---

.travis.yml

Also disable NUMA (as it is not supported on containers) and use Node 6 and 8 for testing.

Travis: Use Cassandra v3.11.2

---

.gitignore
package.json

Replaced Istanbul with nyc

---

.travis.yml

Travis builds are failing. Also added Node 10 to Travis config

Replaced Oracle Java 8 with OpenJDK 8

---

.gitignore
lib/dbutils.js
package.json

Removed core-js dependency from restbase-mod-table-cassandra
